// auto generated by go tool dist
// then edited by hand. oh boy.

// The offsets 0 and 8 are known to:
//../../cmd/6l/pass.c:/D_GS
//cgo/gcc_linux_amd64.c:/^threadentry
//cgo/gcc_darwin_amd64.c:/^threadentry
//
#define get_tls(r)
#define g(r) 0(GS)
#define m(r) 8(GS)
#define gobuf_sp 0
#define gobuf_pc 8
#define gobuf_g 16
#define g_stackguard 0
#define g_stackbase 8
#define g_defer 16
#define g_panic 24
#define g_sched 32
#define g_gcstack 56
#define g_gcsp 64
#define g_gcguard 72
#define g_stack0 80
#define g_entry 88
#define g_alllink 96
#define g_param 104
#define g_status 112
#define g_goid 116
#define g_selgen 120
#define g_waitreason 128
#define g_schedlink 136
#define g_readyonstop 144
#define g_ispanic 145
#define g_m 152
#define g_lockedm 160
#define g_idlem 168
#define g_sig 176
#define g_writenbuf 180
#define g_writebuf 184
#define g_sigcode0 192
#define g_sigcode1 200
#define g_sigpc 208
#define g_gopc 216
#define g_end 224
#define m_g0 0
#define m_morepc 8
#define m_moreargp 16
#define m_morebuf 24
#define m_moreframesize 48
#define m_moreargsize 52
#define m_cret 56
#define m_procid 64
#define m_gsignal 72
#define m_tls 80
#define m_curg 112
#define m_id 120
#define m_mallocing 124
#define m_gcing 128
#define m_locks 132
#define m_nomemprof 136
#define m_waitnextg 140
#define m_dying 144
#define m_profilehz 148
#define m_helpgc 152
#define m_fastrand 156
#define m_ncgocall 160
#define m_havenextg 168
#define m_nextg 176
#define m_alllink 184
#define m_schedlink 192
#define m_machport 200
#define m_mcache 208
#define m_stackalloc 216
#define m_lockedg 224
#define m_idleg 232
#define m_createstack 240
#define m_freglo 496
#define m_freghi 560
#define m_fflag 624
#define m_nextwaitm 632
#define m_waitsema 640
#define m_waitsemacount 648
#define m_waitsemalock 652
#define m_end 656
#define wincall_fn 0
#define wincall_n 8
#define wincall_args 16
#define wincall_r1 24
#define wincall_r2 32
#define wincall_err 40
